# Name of the workflow
name: Hello Wolrd Workflow

# Events that trigger this workflow

on:   
  push:
    branches: [main]
  pull_request:
    branches: [main, staging]

# Jobs to run
jobs:
  greet:
  # The type of runner to use eg windows, ubuntu, mac
    runs-on: ubuntu-latest
    #Steps to excute in this job
    steps:
      #Run a single line command
      - name: Hello 
        run: echo"Hello world"